_attn_implementation_autoset:
    value: true
_name_or_path:
    value: /LOCAL2/hxm826/qwen2.5-vl-safety-model-update
_wandb:
    value:
        cli_version: 0.19.7
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
                - 105
            "3":
                - 7
                - 13
                - 19
                - 23
                - 55
                - 66
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.19.7
            "13": linux-x86_64
acc_steps:
    value: 1
acc_strategy:
    value: token
accelerator_config:
    value:
        dispatch_batches: false
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Qwen2_5_VLWithSafetyClassifiers
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: 151643
check_model:
    value: true
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: 42
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
dispatch_batches:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 100
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
evaluation_strategy:
    value: steps
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_num:
    value: 1
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
galore_config:
    value: null
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: silu
hidden_size:
    value: 3584
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": text_safety
        "1": text_category
        "2": image_safety
        "3": image_category
ignore_data_skip:
    value: false
image_safety_categories:
    value:
        - 'NA: None to Apply'
        - self_harm
        - self_harm_instructions
        - self_harm_intent
        - sexual
        - violence
        - violence_graphic
image_token_id:
    value: 151655
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 18944
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        image_category: 3
        image_safety: 2
        text_category: 1
        text_safety: 0
learning_rate:
    value: 2e-05
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: 0
local_repo_path:
    value: null
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /LOCAL2/hxm826/qwen2.5-vl-safety-model-sft-update/v2-20250313-181914/runs
logging_first_step:
    value: true
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 128000
max_steps:
    value: -1
max_window_layers:
    value: 28
metric_for_best_model:
    value: loss
metric_warmup_step:
    value: 0
min_length:
    value: 0
model/num_parameters:
    value: 8312530994
model_type:
    value: qwen2_5_vl
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 28
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 28
num_key_value_heads:
    value: 4
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
optimizer:
    value: null
output_attentions:
    value: false
output_dir:
    value: /LOCAL2/hxm826/qwen2.5-vl-safety-model-sft-update/v2-20250313-181914
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 151643
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: /LOCAL2/hxm826/qwen2.5-vl-safety-model-update
            bias: none
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 16
            lora_bias: false
            lora_dropout: 0.05
            lora_dtype: null
            lorap_emb_lr: 1e-06
            lorap_lr_ratio: null
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save:
                - v_head
                - classifier
                - score
            peft_type: LORA
            r: 8
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules: (?!^(visual.merger))^(model)(?!.*(lora_A|lora_B|base_layer|emb|wte|shared|lm_head|output|score|v_head|classifier)).*
            task_type: SEQ_CLS
            use_dora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 1
per_device_train_batch_size:
    value: 1
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-06
rope_scaling:
    value:
        mrope_section:
            - 16
            - 24
            - 24
        rope_type: default
        type: default
rope_theta:
    value: 1e+06
run_name:
    value: /LOCAL2/hxm826/qwen2.5-vl-safety-model-sft-update/v2-20250313-181914
safety_rating_map:
    value:
        Safe: 0
        Unsafe: 1
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 100
save_strategy:
    value: steps
save_total_limit:
    value: 3
seed:
    value: 42
sep_token_id:
    value: null
sequence_parallel_size:
    value: 1
skip_memory_metrics:
    value: true
sliding_window:
    value: 32768
split_batches:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
text_safety_categories:
    value:
        - 'NA: None to Apply'
        - harassment
        - harassment_threatening
        - hate
        - hate_threatening
        - illicit
        - illicit_violent
        - self_harm
        - self_harm_instructions
        - self_harm_intent
        - sexual
        - sexual_minors
        - violence
        - violence_graphic
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float16
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
train_dataset_sample:
    value: -1
train_sampler_random:
    value: true
train_type:
    value: lora
transformers_version:
    value: 4.49.0
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
use_sliding_window:
    value: false
video_token_id:
    value: 151656
vision_config:
    value:
        _attn_implementation_autoset: false
        _name_or_path: ""
        add_cross_attention: false
        architectures: null
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: null
        chunk_size_feed_forward: 0
        cross_attention_hidden_size: null
        decoder_start_token_id: null
        depth: 32
        diversity_penalty: 0
        do_sample: false
        early_stopping: false
        encoder_no_repeat_ngram_size: 0
        eos_token_id: null
        exponential_decay_length_penalty: null
        finetuning_task: null
        forced_bos_token_id: null
        forced_eos_token_id: null
        fullatt_block_indexes:
            - 7
            - 15
            - 23
            - 31
        hidden_act: silu
        hidden_size: 1280
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        in_channels: 3
        in_chans: 3
        intermediate_size: 3420
        is_decoder: false
        is_encoder_decoder: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        length_penalty: 1
        max_length: 20
        min_length: 0
        model_type: qwen2_5_vl
        no_repeat_ngram_size: 0
        num_beam_groups: 1
        num_beams: 1
        num_heads: 16
        num_return_sequences: 1
        out_hidden_size: 3584
        output_attentions: false
        output_hidden_states: false
        output_scores: false
        pad_token_id: null
        patch_size: 14
        prefix: null
        problem_type: null
        remove_invalid_values: false
        repetition_penalty: 1
        return_dict: true
        return_dict_in_generate: false
        sep_token_id: null
        spatial_merge_size: 2
        spatial_patch_size: 14
        suppress_tokens: null
        task_specific_params: null
        temperature: 1
        temporal_patch_size: 2
        tf_legacy_loss: false
        tie_encoder_decoder: false
        tie_word_embeddings: true
        tokenizer_class: null
        tokens_per_second: 2
        top_k: 50
        top_p: 1
        torch_dtype: float16
        torchscript: false
        typical_p: 1
        use_bfloat16: false
        window_size: 112
vision_end_token_id:
    value: 151653
vision_start_token_id:
    value: 151652
vision_token_id:
    value: 151654
vocab_size:
    value: 152064
warmup_ratio:
    value: 0.05
warmup_steps:
    value: 0
weight_decay:
    value: 0.1
